### Training a Decision Tree Classifier

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets


# Load data
iris = datasets.load_iris()
features = iris.data
target = iris.target


# Create decision tree classifier object
decisiontree = DecisionTreeClassifier(random_state=0)

# Train model
model = decisiontree.fit(features, target)

In [5]:
observation = [[ 5, 4, 3, 2]]
model.predict(observation)

array([1])

In [4]:
model.predict_proba(observation)

array([[0., 1., 0.]])

#### Change the criterion of split

In [6]:
decisiontree_entropy = DecisionTreeClassifier(criterion='entropy', random_state=0)

### Training a Regressor

In [9]:
# Load libraries
from sklearn.tree import DecisionTreeRegressor
from sklearn import datasets


# Load data with only two features
boston = datasets.load_boston()
features = boston.data[:,0:2]
target = boston.target


# Create decision tree classifier object
decisiontree = DecisionTreeRegressor(random_state=0)


# Train model
model = decisiontree.fit(features, target)

c:\users\prem\miniconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [10]:
# Make new observation
observation = [[0.02, 16]]

# Predict observation's value
model.predict(observation)

array([33.])

In [11]:
#Create decision tree classifier object using entropy
decisiontree_mae = DecisionTreeRegressor(criterion="mae", random_state=0)

# Train model
model_mae = decisiontree_mae.fit(features, target)

c:\users\prem\miniconda3\lib\site-packages\sklearn\tree\_classes.py:366: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  warnings.warn(
